### ISSUE TITLE
Transformer includes - Call to a member function setCurrentScope() on string

### ISSUE THREAD

**Issue by kurbar** [thephpleague/fractal#499]
I'm trying to use the includes logic to include another collection. However, when trying to include, I'm getting an error whether I'm using `$defaultIncludes` or including them manually via `?include=`: `Call to a member function setCurrentScope() on string`.

Analysing the stack trace. The initial transformers `->fireTransformer` has it as an object, but the second call (when it calls the include), `->fireTransformer` calls it as a string and I think that is why it is failing. But I don't understand quite right why it is happening.

I'm using Fractal version 0.17.0 and PHP 7.4

My transformers is pretty straightforward:

```
// DraftTransformer.php
class DraftTransformer extends TransformerAbstract
{

    protected $availableIncludes = [
        'attachments',
    ];

    public function transform(Draft $draft)
    {
        return [
            'id' => (int) $draft->id,
            'form' => $draft->form,
            'meta' => [
                'has_attachments' => $draft->getMedia('attachments')->count() > 0,
                'created_at' => $draft->created_at->toDateTimeString(),
                'updated_at' => $draft->updated_at->toDateTimeString(),
            ]
        ];
    }

    public function includeAttachments(Draft $draft)
    {
        $attachments = $draft->getMedia('attachments');
        return $this->collection($attachments, AttachmentTransformer::class);
    }
}
```

```
// AttachmentTransformer
class AttachmentTransformer extends TransformerAbstract
{

    public function transform(Media $attachment)
    {
        return [
            'id' => (int) $attachment->id,
            'name' => $attachment->file_name,
            'contentType' => mime_content_type($attachment->getPath()),
            'size' => $attachment->size,
        ];
    }
}
```

Stack trace:
```
Call to a member function setCurrentScope() on string {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setCurrentScope() on string at /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php:406)
[stacktrace]
#0 /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php(349): League\\Fractal\\Scope->fireTransformer('Zone\\\\Webmail\\\\Ma...', Object(Spatie\\MediaLibrary\\Models\\Media))
#1 /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php(235): League\\Fractal\\Scope->executeResourceTransformers()
#2 /Users/karl/projects/zone/api/vendor/league/fractal/src/TransformerAbstract.php(162): League\\Fractal\\Scope->toArray()
#3 /Users/karl/projects/zone/api/vendor/league/fractal/src/TransformerAbstract.php(128): League\\Fractal\\TransformerAbstract->includeResourceIfAvailable(Object(League\\Fractal\\Scope), Object(Zone\\Webmail\\Mailbox\\Models\\Draft), Array, 'attachments')
#4 /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php(435): League\\Fractal\\TransformerAbstract->processIncludedResources(Object(League\\Fractal\\Scope), Object(Zone\\Webmail\\Mailbox\\Models\\Draft))
#5 /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php(411): League\\Fractal\\Scope->fireIncludedTransformers(Object(Zone\\Webmail\\Mailbox\\Transformers\\DraftTransformer), Object(Zone\\Webmail\\Mailbox\\Models\\Draft))
#6 /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php(346): League\\Fractal\\Scope->fireTransformer(Object(Zone\\Webmail\\Mailbox\\Transformers\\DraftTransformer), Object(Zone\\Webmail\\Mailbox\\Models\\Draft))
#7 /Users/karl/projects/zone/api/vendor/league/fractal/src/Scope.php(235): League\\Fractal\\Scope->executeResourceTransformers()
#8 /Users/karl/projects/zone/core/src/TransformerHelper.php(59): League\\Fractal\\Scope->toArray()
#9 /Users/karl/projects/zone/core/src/Http/Response.php(48): Zone\\Webmail\\Core\\TransformerHelper->item(Object(Zone\\Webmail\\Mailbox\\Models\\Draft), Object(Zone\\Webmail\\Mailbox\\Transformers\\DraftTransformer))
#10 /Users/karl/projects/zone/mailbox/src/Controllers/DraftController.php(69): Zone\\Webmail\\Core\\Http\\Response->item(Object(Zone\\Webmail\\Mailbox\\Models\\Draft), Object(Zone\\Webmail\\Mailbox\\Transformers\\DraftTransformer))
#11 /Users/karl/projects/zone/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Zone\\Webmail\\Mailbox\\Controllers\\DraftController->get('5baab08427b25a6...', '3278')
#12 /Users/karl/projects/zone/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Zone\\Webmail\\Mailbox\\Controllers\\DraftController), 'get')
#13 /Users/karl/projects/zone/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#14 /Users/karl/projects/zone/api/app/Http/Middleware/ModuleRouting.php(32): Illuminate\\Routing\\Route->run()
...
"}
```

**Comment by kurbar** [comment]
Foolish me. I did not call the AttachmentTransformer as an instance.
```
return $this->collection($attachments, new AttachmentTransformer);
```
